name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api-gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          push: true
          tags: \${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Build and push customer-services image
        uses: docker/build-push-action@v4
        with:
          context: ./customer-services
          push: true
          tags: \${{ secrets.DOCKER_USERNAME }}/customer-services:latest

      - name: Build and push inventory-services image
        uses: docker/build-push-action@v4
        with:
          context: ./inventory-services
          push: true
          tags: \${{ secrets.DOCKER_USERNAME }}/inventory-services:latest

      - name: Build and push menu-services image
        uses: docker/build-push-action@v4
        with:
          context: ./menu-services
          push: true
          tags: \${{ secrets.DOCKER_USERNAME }}/menu-services:latest

      - name: Build and push order-services image
        uses: docker/build-push-action@v4
        with:
          context: ./order-services
          push: true
          tags: \${{ secrets.DOCKER_USERNAME }}/order-services:latest

      - name: Build and push payment-services image
        uses: docker/build-push-action@v4
        with:
          context: ./payment-services
          push: true
          tags: \${{ secrets.DOCKER_USERNAME }}/payment-services:latest
