name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: saniazaheer
          password: 2235766$@

      - name: Build and push api-gateway image
        uses: docker/build-push-action@v4
        with:
          context: Cafe_Management_System/api-gateway
          push: true
          tags: saniazaheer/api-gateway:latest

      - name: Build and push customer-services image
        uses: docker/build-push-action@v4
        with:
          context: Cafe_Management_System/customer-services
          push: true
          tags: saniazaheer/customer-services:latest

      - name: Build and push inventory-services image
        uses: docker/build-push-action@v4
        with:
          context: Cafe_Management_System/inventory-services
          push: true
          tags: saniazaheer/inventory-services:latest

      - name: Build and push menu-services image
        uses: docker/build-push-action@v4
        with:
          context: Cafe_Management_System/menu-services
          push: true
          tags: saniazaheer/menu-services:latest

      - name: Build and push order-services image
        uses: docker/build-push-action@v4
        with:
          context: Cafe_Management_System/order-services
          push: true
          tags: saniazaheer/order-services:latest

      - name: Build and push payment-services image
        uses: docker/build-push-action@v4
        with:
          context: Cafe_Management_System/payment-services
          push: true
          tags: saniazaheer/payment-services:latest
